env:
  browser: true
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
rules:
  no-mixed-spaces-and-tabs:
    - error
  indent:
    - error
    - 4
  no-trailing-spaces:
    - error
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console: off
  no-var:
    - error
  eqeqeq:
    - error
  brace-style:
    - error
    - allman